# Generated by Django 4.2.6 on 2023-10-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companylogin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tests',
            name='status',
            field=models.CharField(default='Active', max_length=128),
        ),
    ]
