# Generated by Django 4.2.6 on 2023-10-21 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companylogin', '0002_tests_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_name', models.CharField(max_length=128)),
                ('address', models.PositiveIntegerField()),
                ('phone', models.PositiveIntegerField()),
                ('email', models.CharField(default='Active', max_length=128)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/center/')),
                ('password', models.CharField(default='Active', max_length=128)),
            ],
        ),
    ]
