# Generated by Django 4.2.6 on 2023-10-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companylogin', '0004_alter_centers_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centers',
            name='address',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='centers',
            name='center_name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='centers',
            name='email',
            field=models.CharField(default='Active', max_length=256),
        ),
        migrations.AlterField(
            model_name='centers',
            name='phone',
            field=models.CharField(max_length=256),
        ),
    ]
