# Generated by Django 4.2.6 on 2023-10-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companylogin', '0005_alter_centers_address_alter_centers_center_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centers',
            name='email',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='centers',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
