# Generated by Django 4.2.6 on 2023-10-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companylogin', '0006_alter_centers_email_alter_centers_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centers',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profile_pic/center/'),
        ),
    ]
