# Generated by Django 4.2.6 on 2023-10-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companylogin', '0007_alter_centers_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centers',
            name='profile_pic',
            field=models.FileField(default=None, null=True, upload_to='profile_pic/center/'),
        ),
    ]
