# Generated by Django 4.2.6 on 2023-10-30 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_zone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
