# Generated by Django 3.2.5 on 2023-12-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_zone', '0002_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='contact_data',
        ),
    ]
