# Generated by Django 4.2.6 on 2023-10-31 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_zone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('center_code', models.CharField(max_length=10, unique=True)),
                ('center_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
                ('email_id', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
    ]
