# Generated by Django 4.2.6 on 2023-10-31 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_zone', '0002_center'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Center',
            new_name='addnewCenterlist',
        ),
    ]
